'''
Created on Mar 27, 2013
'''

tagDict = {
            'ZZ' : 'Incomplete',       
            'FV' : 'Favorite',      
            'HL' : 'Hi-light',      
            'SE' : 'Something Else',    
            'AC' : 'Actress',

            'VY' : 'Very Young',     
            'YN' : 'Young Girls', 
            'MA' : 'Mature Women',    
            'VD' : 'Very Old',   
            'CP' : 'Creampie',       
            'CD' : 'CP Dedicated',     
            'LE' : 'Lesbian', 
            'SG' : 'School Girl',    
            'ST' : 'Story',     
            'RL' : 'Realism',         
            'NP' : 'Normal People',     
            'LB' : 'Lubed',  
            'LO' : 'Lolita',           
            'HF' : 'HOT Fucking',    
            
            'FN' : 'Funny',     
            'WD' : 'Weird',            
            'BU' : 'Bully',            
            'BM' : 'Blackmail',         
            'EM' : 'Embarrassing',    
            'TS' : 'Teasing',        
            'SY' : 'Shy',            
            'FA' : 'Fantasy',        
            'GA' : 'Game',             
            'WR' : 'Wrestling',        
            'DR' : 'Doctor',         
            'DG' : 'Drugs/Drinks',    
            'SC' : 'School',         
            'PB' : 'Public',            
            'SR' : 'Sharking',       
            'RP' : 'Role-playing',    
            'CO' : 'Cosplay',        
            'OG' : 'Orgy',            
            'SL' : 'Sleeping',        
           
            'RA' : 'Rape',             
            'CR' : 'Crying',         
            'LD' : 'Loud',             
            'RC' : 'Rough Core',     
            'TO' : 'Torture (Mild)',        
            'TR' : 'Torture (Hard)',         
            'GR' : 'Gang Rape',  
            'FC' : 'Forced Creampie',
            'HE' : 'Heinous',
            'IS' : 'Insemination',    
            'AB' : 'Abused',    
            'PN' : 'Punishment',        
            'CH' : 'Chikan',      
            'BD' : 'Bondage',       
            'FE' : 'Fear',       
            'OR' : 'Orgasm',            
            
            'SP' : 'Sperm',            
            'PE' : 'Peeing',            
            'PO' : 'Poop',            
            'VO' : 'Vomit',            
            
            'MO' : 'Mother-Son Incest',        
            'FD' : 'Father-Daughter Incest',
            'BS' : 'Brother-Sister Incest', 
            'MD' : 'Mother-Daughter Incest',
            'FI' : 'Faux Incest',     
            'EF' : 'Extended Family Incest',
            'JF' : 'Jumble Family Incest',    
            'RI' : 'Realistic Incest',    
            'GI' : 'Goofy Incest',   
            'MU' : 'Mutual Incest',            
            'FR' : 'Forced Incest',            
            'PR' : 'Perverse Incest',        
            'BL' : 'Blood Related Incest',    
            
            'VR' : 'Voyeur-real',     
            'VP' : 'Voyeur-pseudo',     
            'VF' : 'Voyeur-fake',    
            'MB' : 'Masturbation',   
            'WC' : 'Toilet',            
            
            'U14' : 'Under 14',        
            'O14' : 'Over 14',        
            'AD' : 'Adult',            
            
            'FO' : 'Foreign',        
            'QV' : 'Quality Video',    
            'BQ' : 'Bad Quality',    
            'UC' : 'Uncensored',       
            'CL' : 'Collection',        
            
            'GN' : 'Ganguro',        
            'TN' : 'Tanned',            
            'FT' : 'Fit',             
            'MS' : 'Muscle',         
            'SK' : 'Skinny',       
            'CB' : 'Chubby',            
            'DA' : 'Dat Ass-et',        
            'TI' : 'Tiny',            
            'TL' : 'Tall',            
            'BG' : 'Big Girl',        
            'SH' : 'Short Hair',        
            'TB' : 'Tomboy',            
            'CU' : 'Cute',            
            'VI' : 'Virgin-al',        
            'AV' : 'Acted Virgin',    
            'CS' : 'Curious',        
            'GF' : 'Goofy',          
            'FB' : 'Full-bodied',    
                    
            'MUS' : 'Muscle',        
            'BAK' : 'Bakky Series',    
            'N24' : 'Night24',        
            'RRA' : 'Real Rape',        
            'CND' : 'Chikan Nakadashi',
            'GQU' : 'G-Queen',        
            'RTG' : 'Rocket Games',    
            'SPK' : 'SpikeSpen' 
           }



